import type { Theme, User, Activity, HenkatenEvent } from './types';

export const defaultThemes: Theme[] = [
  { id: 't1', name: 'O/S 103KI', color: '#3b82f6' },
  { id: 't2', name: 'O/S K2G', color: '#8b5cf6' },
  { id: 't3', name: 'Adequação L/O Format. Carros', color: '#06b6d4' },
  { id: 't4', name: 'Alt. de embalagem Eixo', color: '#f59e0b' },
  { id: 't5', name: 'Extra Fluxo', color: '#f97316' },
  { id: 't6', name: 'Pendências INFRA', color: '#ef4444' },
  { id: 't7', name: 'Transf. Dep. F', color: '#10b981' },
  { id: 't8', name: 'P P Dinâmico CQ', color: '#ec4899' },
  { id: 't9', name: 'Pintura Hines', color: '#6366f1' },
  { id: 't10', name: 'Adequação L/O Format. Carros', color: '#06b6d4' },
];

export const defaultUsers: User[] = [
  {
    id: 'u1',
    name: 'RELDERY ASSUNCAO',
    username: 'reldery_assuncao',
    password: '123',
    role: 'Administrador',
    email: 'reldery@admin.com',
    color: '#ef4444',
    permissions: {
      atividades: { view: true, edit: true, delete: true },
      henkatens: { view: true, edit: true, delete: true },
      cadastros: { view: true, edit: true, delete: true },
      usuarios: { view: true, edit: true, delete: true },
    }
  },
  {
    id: 'u2',
    name: 'MARCOS PAULO',
    username: 'marcos_paulo',
    password: '123',
    role: 'Gestão',
    email: 'marcos@gestao.com',
    color: '#8b5cf6',
    permissions: {
      atividades: { view: true, edit: true, delete: true },
      henkatens: { view: true, edit: true, delete: true },
      cadastros: { view: true, edit: true, delete: true },
      usuarios: { view: false, edit: false, delete: false },
    }
  },
  {
    id: 'u3',
    name: 'HUDSON SILVA',
    username: 'hudson_silva',
    password: '123',
    role: 'Analista',
    email: 'hudson@analista.com',
    color: '#10b981',
    permissions: {
      atividades: { view: true, edit: true, delete: true },
      henkatens: { view: true, edit: true, delete: false },
      cadastros: { view: false, edit: false, delete: false },
      usuarios: { view: false, edit: false, delete: false },
    }
  },
];

export const defaultActivities: Activity[] = [
  {
    id: 'a1',
    planejamento: '2026-03-09',
    descricao: 'Outsourcing - análise de área (Dep. Externo / DCC) - Consolidação dos itens (102 + 103KI)',
    tema: 't1',
    responsavel: 'u1',
    prioridade: 'Média',
    dataPrevistaFinalizacao: '2026-03-10',
    percentualAndamento: 100,
    dataFinalizada: '2026-03-11',
    diasEsperadosConclusao: 2,
    esforcoRealizado: 2,
    status: 'FINALIZADA',
    week: 'W2 - Mar',
  },
  {
    id: 'a2',
    planejamento: '2026-03-10',
    descricao: 'Outsourcing - análise de área (Dep. Externo / DCC) - Input das informações de embalagens / mix / utilização',
    tema: 't1',
    responsavel: 'u1',
    prioridade: 'Média',
    dataPrevistaFinalizacao: '2026-03-11',
    percentualAndamento: 100,
    dataFinalizada: '2026-03-12',
    diasEsperadosConclusao: 2,
    esforcoRealizado: 2,
    status: 'FINALIZADA',
    week: 'W2 - Mar',
  },
  {
    id: 'a3',
    planejamento: '2026-03-16',
    descricao: 'Levantar os impactos para retirada do processo de formatação da carcaça e cabeçote do K2G - Bancada',
    tema: 't2',
    responsavel: 'u1',
    prioridade: 'Média',
    dataPrevistaFinalizacao: '2026-03-17',
    percentualAndamento: 100,
    dataFinalizada: '2026-03-16',
    diasEsperadosConclusao: 0,
    esforcoRealizado: 0,
    status: 'FINALIZADA',
    week: 'W3 - Mar',
  },
  {
    id: 'a4',
    planejamento: '2026-03-17',
    descricao: 'Validar com a operação a formatação do tubo coluna do K1S - OPERAÇÃO',
    tema: 't1',
    responsavel: 'u2',
    prioridade: 'Alta',
    dataPrevistaFinalizacao: '2026-03-18',
    percentualAndamento: 0,
    diasEsperadosConclusao: -11,
    esforcoRealizado: 0,
    status: 'PENDENTE',
    week: 'W3 - Mar',
  },
  {
    id: 'a5',
    planejamento: '2026-03-09',
    descricao: 'Avaliar pendências de área Hines - Bloco 108',
    tema: 't6',
    responsavel: 'u2',
    prioridade: 'Baixa',
    dataPrevistaFinalizacao: '2026-03-11',
    percentualAndamento: 100,
    dataFinalizada: '2026-03-12',
    diasEsperadosConclusao: 3,
    esforcoRealizado: 3,
    status: 'FINALIZADA',
    week: 'W2 - Mar',
  },
  {
    id: 'a6',
    planejamento: '2026-03-24',
    descricao: 'Identificação do porta palete dinâmico CQ',
    tema: 't8',
    responsavel: 'u2',
    prioridade: 'Alta',
    dataPrevistaFinalizacao: '2026-03-25',
    percentualAndamento: 100,
    dataFinalizada: '2026-03-24',
    diasEsperadosConclusao: -4,
    esforcoRealizado: 0,
    status: 'PENDENTE',
    week: 'W4 - Mar',
  },
  {
    id: 'a7',
    planejamento: '2026-03-09',
    descricao: 'Validar lógica de identificação do layout (Coall)',
    tema: 't10',
    responsavel: 'u3',
    prioridade: 'Alta',
    dataPrevistaFinalizacao: '2026-03-09',
    percentualAndamento: 100,
    dataFinalizada: '2026-03-14',
    diasEsperadosConclusao: 5,
    esforcoRealizado: 5,
    status: 'FINALIZADA',
    week: 'W2 - Mar',
  },
  {
    id: 'a8',
    planejamento: '2026-03-23',
    descricao: 'Proposta bancada amortecedor na nova área de desconsolidação',
    tema: 't10',
    responsavel: 'u3',
    prioridade: 'Alta',
    dataPrevistaFinalizacao: '2026-03-25',
    percentualAndamento: 0,
    diasEsperadosConclusao: -5,
    esforcoRealizado: 0,
    status: 'PENDENTE',
    week: 'W4 - Mar',
  },
  {
    id: 'a9',
    planejamento: '2026-03-26',
    descricao: 'Acompanhamento de Infra, elétrica e lógica DCC',
    tema: 't5',
    responsavel: 'u3',
    prioridade: 'Alta',
    dataPrevistaFinalizacao: '2026-03-27',
    percentualAndamento: 90,
    diasEsperadosConclusao: 0,
    esforcoRealizado: 0,
    status: 'EM ANDAMENTO',
    week: 'W4 - Mar',
  },
];

export const defaultHenkatens: HenkatenEvent[] = [
  {
    id: 'h1',
    date: '2026-03-02',
    endDate: '2026-03-03',
    type: 'PP1',
    title: 'Projeto 1',
    description: 'Fase inicial',
    status: 'Confirmado',
  },
  {
    id: 'h2',
    date: '2026-03-10',
    type: 'PP2',
    title: 'Projeto 1',
    description: 'Fase secundária do projeto',
    status: 'Planejado',
  },
  {
    id: 'h3',
    date: '2026-03-18',
    type: 'MP',
    title: 'Início MP',
    description: 'Aprovação final',
  },
  {
    id: 'h4',
    date: '2026-03-25',
    type: 'TRY OUT',
    title: 'Teste de Try Out',
    status: 'Sem Informação'
  },
  {
    id: 'h5',
    date: '2026-03-27',
    type: 'PP1',
    title: 'Postergado PP1 teste',
    status: 'Postergado',
    postponedDate: '2026-04-05'
  },
  {
    id: 'h6',
    date: '2026-03-31',
    type: 'PP2',
    title: 'Cancelado PP2',
    status: 'Cancelado'
  }
];
